{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-enterprise
  namespace: {{ .Release.Namespace }}
  labels:
    app: terraform-enterprise
  annotations:
    checkov.io/skip1: CKV_K8S_13= The Helm chart should remain similar to the open source original.
    checkov.io/skip2: CKV_K8S_43= The Helm chart should remain similar to the open source original.
    checkov.io/skip3: CKV_K8S_31= The Helm chart should remain similar to the open source original.
    checkov.io/skip4: CKV_K8S_35= The Helm chart should remain similar to the open source original.
    checkov.io/skip5: CKV_K8S_23= The Helm chart should remain similar to the open source original.
    checkov.io/skip6: CKV_K8S_22= The Helm chart should remain similar to the open source original.
    checkov.io/skip7: CKV_K8S_37= The Helm chart should remain similar to the open source original.
    checkov.io/skip8: CKV_K8S_38= The Helm chart should remain similar to the open source original.
    checkov.io/skip9: CKV_K8S_8= The Helm chart should remain similar to the open source original.
    checkov.io/skip10: CKV_K8S_28= The Helm chart should remain similar to the open source original.
    checkov.io/skip11: CKV_K8S_20= The Helm chart should remain similar to the open source original.
    checkov.io/skip12: CKV_K8S_11= The Helm chart should remain similar to the open source original.
    checkov.io/skip13: CKV2_K8S_6= The Helm chart should remain similar to the open source original.
    checkov.io/skip14: CKV_K8S_40= The Helm chart should remain similar to the open source original.
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: terraform-enterprise
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/env-config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.pod.annotations }}
        {{- toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
        {{- if .Values.tfe.metrics.enable }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.tfe.metrics.httpPort }}"
        prometheus.io/scrape: "true"
        {{- end }}
      labels:
        app: terraform-enterprise
        {{- if .Values.pod.labels }}
        {{- toYaml .Values.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
        - name: certificates
          secret:
            secretName: {{ .Values.tls.certificateSecret }}
        {{- if .Values.tls.caCertData }}
        - name: ca-certificates
          secret:
            secretName: terraform-enterprise-ca-certificates
        {{- end }}
        {{- if .Values.csi.enabled }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.csi.secretProviderClass }}"
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      {{- if .Values.serviceAccount.name}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- else }}
      serviceAccountName: {{ .Release.Namespace }}
      {{- end }}
      {{- end }}
      initContainers:
        {{ toYaml .Values.initContainers | nindent 8}}
      containers:
      - name: terraform-enterprise
        command:
          - /bin/sh
          - '-c'
          - |
            sed -i '/^[ ]\{2\}pool:/a\ \ schema_search_path: "public,ibm_extension"' /app/config/database.yml
            sed -i 's/server_names_hash_bucket_size 128;/server_names_hash_bucket_size 256;/' /etc/nginx/nginx.conf.tmpl
            /usr/local/bin/supervisord-run
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
        {{- if and .Values.openshift.enabled (not .Values.container.securityContext) }}
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
        {{- else }}
        {{- toYaml .Values.container.securityContext | nindent 10 }}
        {{- end }}
        {{- with (include "helpers.list-valueFrom-variables" .) }}
        env:
          {{- . | indent 10 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: terraform-enterprise-env-config
        {{- if .Values.env.configMapRefs }}
          {{- range .Values.env.configMapRefs }}
          - configMapRef:
              name: {{ .name }}
          {{- end }}
        {{- end }}
          - secretRef:
              name: terraform-enterprise-env-secrets
        {{- if .Values.env.secretRefs }}
          {{- range .Values.env.secretRefs }}
          - secretRef:
              name: {{ .name }}
          {{- end }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: {{ .Values.tfe.readinessProbePath | default "/_health_check" }}
            port: {{ .Values.tfe.privateHttpPort }}
            scheme: {{ .Values.tfe.readinessProbeScheme | default "HTTP"  }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: certificates
            mountPath: {{ .Values.tls.certMountPath }}
            subPath: tls.crt
          - name: certificates
            mountPath: {{ .Values.tls.keyMountPath }}
            subPath: tls.key
          {{- if .Values.tls.caCertData }}
          - name: ca-certificates
            mountPath: {{ include "cacert.path" . }}
            subPath: {{ .Values.tls.caCertFileName }}
          {{- end }}
          {{- if .Values.csi.enabled }}
          - name: secrets-store
            mountPath: "{{ .Values.csi.mountPath }}"
            readOnly: true
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.tfe.privateHttpPort }}
        - containerPort: {{ .Values.tfe.privateHttpsPort }}
        {{- if .Values.tfe.metrics.enable }}
        - containerPort: {{.Values.tfe.metrics.httpPort}}
        - containerPort: {{.Values.tfe.metrics.httpsPort}}
        {{- end }}
